### ISSUE TITLE
"Empty set" ambiguity

### ISSUE THREAD

**Issue by lann** [lann/wasm-wave#17]
An "empty set" value `{}` has two possible interpretations: a `flags` value with zero flags set or a `record` value with all field values set to `none` (because "Record entries with the option-typed value none may be omitted").

The WAVE parser in this repo avoids this ambiguity because it is type-driven, but any alternative implementation that wanted to parse to an AST would need to address it.

I see two obvious options:

- Disallow `{}` for records. A `record` with all fields values set to `none` would need to specify at least one of those fields explicitly, e.g. `{optional-field: none}`
- Give `{}` its own formal rule (e.g. `empty-set := '{' '}'`) and accept the AST ambiguity. AST ambiguity is already present for other Component Model value representations such as various number types and `bool`s (vs variant case labels).

**Comment by sunfishcode** [comment]
Additional options:
 - Change flags to eg. `|read, write|`. (I know that looks like a closure in Rust/Ruby/etc., but I guess in context it'll be fine.)
 - Parse `{_}` as "record without explicit fields", and parse `{}` as flags.

**Comment by lann** [comment]
Another option: `{:}` as "record without explicit fields", which would lead to the nice property that records always contain a `:` between braces.

**Comment by lann** [comment]
Yet another option: require that empty flag sets be expressed as `∅` :smile:

**Comment by lann** [comment]
#20 adopts `{:}` for "empty" records.
