### ISSUE TITLE
Multi-line/raw strings

### ISSUE THREAD

**Issue by lann** [lann/wasm-wave#21]
This doesn't have existing WIT design to draw from so there are some ideas drawn from other languages:

- Repeated delimiter chars allows some armoring against inner delimiters like Rust's `r###"..."###`
- Leading newline and common indent in multi-line strings is stripped, like Python's docstring processing

The rules are intended to make these strings easy for humans to read and write; WAVE encoders generally wouldn't produce them.

## Examples

```
%"raw string; no escape: \n"%
```
→ `"raw string; no escape: \\n"`

```
%"Starting with a non-newline
  preserves indents."%
```
→ `"Starting with a non-newline\n  preserves indents."`

```
%"

A single leading newline is stripped."%
```
→ `"\nA single leading newline is stripped."`

```
%"
Trailing newlines are preserved
"%
```
→ `"Trailing newlines are preserved\n"`

```
%"
  Starting with a newline
  strips common indents.
"%
```
→ `"Starting with a newline\nstrips common indents.\n"`

```
%%"Wider delimiters allows "% <- delimiters inside"%%
```
→ `"Wider delimiters allows \"% <- delimiters inside"`

## Raw string

One or more `%`s, then `"`, then any UTF-8 characters until the closing delimiters: `"` followed by the same number of `%`s as the opening delimiter:

```ruby
/(%+)".*?"(\1)/
```

`%"…"%` ≡ `%%"…"%%` ≡ `%%%%%"…"%%%%%`

### Multi-line post-processing

> Note: While described as a separate post-processing step for clarity this can be implemented as part of normal parsing.

Newline means `"\r\n"` or `"\n"`. Space means `" "`.

When a raw string starts with a newline, multi-line post-processing applies to the string contents:

- Skip the leading newline
- Skip any leading spaces; the number of spaces skipped is the `indent` of the string
- Loop:
  - Skip spaces until:
    - `indent` spaces have been skipped: continue
    - end-of-string is reached: return the output
    - a non-space character is found: return "invalid indent" error
  - Copy characters verbatim into the output until:
    - end-of-string is reached: return the output
    - a newline is found: copy the newline to the output and continue the loop

> It might be better to trigger these rules more explicitly than "when a raw string starts with a newline"...

**Comment by sunfishcode** [comment]
> ```
> %"Starting with a non-newline
>   preserves indents."%
> ```

This means that auto-indenters either change the meaning of the code, or can't indent that line to match the surrounding code. For comparison, Python docstrings always strip indentation and just ignore the first line's indentation.

What would you think about disallowing newlines unless a string begins with a newline? That would leave us with two visually distinct forms:

```
  %"hello in one line"%
```
and
```
  %"
     hello
     with
     newlines
  "%
```

That way, instead of two rules for how indentation behaves, there's just one rule, and it's basically the same as python docstrings.


> Skip the leading newline
> Skip any leading spaces; the number of spaces skipped is the `indent` of the string

This precludes multi-line strings that start with whitespace, which is uncommon but does happen.

What would you think of adopting the Python docstrings rule of using the minimum indentation of any line? That still has the requirement that *some* line start with non-whitespace, which is still a little odd, but less so.

**Comment by lann** [comment]
> What would you think about disallowing newlines unless a string begins with a newline? That would leave us with two visually distinct forms:

Ah good idea. I was a little worried about that ambiguity.

> This precludes multi-line strings that start with whitespace, which is uncommon but does happen.

I think that's fine. This is intended to be a convenience for authoring a limited (but common) kind of content. You can always fall back to regular strings.

**Comment by lann** [comment]
> What would you think of adopting the Python docstrings rule of using the minimum indentation of any line?

I suppose this would retain the ability to represent (almost) any text in this form [edit: which, re-reading your comment, is exactly what you were saying :sweat_smile:] which is appealing, and it wouldn't make any difference in most common cases. The downsides are (slightly) more complex parsing and a higher chance of hiding mistakes, but maybe that is worth it.

**Comment by lann** [comment]
Swift has [an interesting variation](https://docs.swift.org/swift-book/documentation/the-swift-programming-language/stringsandcharacters/#Multiline-String-Literals):

```
x = """
     Indent is determined by the closing delimiter,
    so all strings can be represented.
   """
```
&rarr; `"  Indent is determined by the closing delimiter,\n so all strings can be represented."`

**Comment by lann** [comment]
Superseded by #29
