### ISSUE TITLE
Multiline strings Ⅲ

### ISSUE THREAD

**Issue by lann** [lann/wasm-wave#29]
> This design is adapted from [Swift's multiline string syntax](https://docs.swift.org/swift-book/documentation/the-swift-programming-language/lexicalstructure#String-Literals).

## Examples

```python
"""
A "multiline" string
"""
```
&rarr;
```python
"A \"multiline\" string"
```

---
```python
{
  description: """
    Common indent
    is stripped
    """,
  body: """
      Extra indent allowed
     on any content line
    """,
}
```
&rarr;
```python
{
  description: "Common indent\nis stripped",
  body: "  Extra indent allowed\n on any content line",
}
```
---
```python
"""

Leading and trailing lines preserved

"""
```
&rarr;
```python
"\nLeading and trailing lines preserved\n"
```

## Description

A multiline string consists of:

- the opening delimiter: `"""\n`
- any number of content lines: `(?<indent> *)[^\n]*\n` (ignoring escapes for brevity)
  - normal string escape sequences apply; the only mandatory escapes are `\\` and any `\"` necessary to break up a substring of `"""`
  - > TBD: special-case unindented blank lines?
- the closing delimiter: `(?<indent> *)"""`

The content lines are post-processed: the number of `indent` spaces in the closing delimiter is considered the indent level of the entire string and stripped from each content line. Content lines are joined with newlines to form the output.

> TBD: strip trailing `\r`?

## Follow-up: Raw Strings

This would be a separate (overlapping) feature, allowing both single-line raw strings `%"which may not contain newlines"%` and:

```python
%"""
  Multi-line strings which do not interpret \ escapes
  and permit """unescaped multiline string delimiters"""
  """%
```
%rarr;
```python
"Multi-line strings which do not interpret \\ escapes\nand permit \"\"\"unescaped multiline string delimiters\"\"\""
```

See #21 for previous discussion and #26 for an alternative proposal.

**Comment by lann** [comment]
@sunfishcode I think this one is my least-unfavorite so far. I don't _love_ the dedent logic - it will probably trip up authors at first - but there are fewer _subtle_ mistakes to be made I think.

**Comment by sunfishcode** [comment]
I don't see any deal-breakers here.

#26 has some details to be worked out yet, but it feels like the next step should be to make an aesthetic judgement call. Maybe we should seek input from more people? So like this:
```
package({
  name: "my-pkg",
  version: "1.2.3",

  scripts: {
    build: %"""
        echo "foo"
        node -c "console.log('hello, world!');"
        echo "foo" > some-file.txt
        """%,
    clean: %"""
      rm -rf output
      """%
  },

  regex: %"^[\w-\.]+"%
})
```

or this:
```
package({
  name: "my-pkg",
  version: "1.2.3",

  scripts: {
    build:
      > echo "foo"
      > node -c "console.log('hello, world!');"
      > echo "foo" > some-file.txt
    clean:
      > rm -rf output
  },

  regex: > ^[\w-\.]+
})
```

**Comment by sunfishcode** [comment]
I've now done some informal polling and #26 hasn't caught on, so I've now closed it and think this `"""` approach makes sense to pursue.
